# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventindexpagefeaturedpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='eventpagerelateddocument',
            name='page',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='phone',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone'),
        ),
        migrations.DeleteModel(
            name='EventPageRelatedDocument',
        ),
    ]
