version: '3.5'
services:

  redis:
    image: redis

  database:
    image: postgres:9.6
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: hra
      POSTGRES_USER: hra
      POSTGRES_PASSWORD: hra

  search:
    image: elasticsearch:5.3
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data

  web:
    depends_on:
      - redis
      - database
      - search
      - localstack
    build: .
    command: python /app/manage.py runserver 0.0.0.0:80
    ports:
      - 8000:80
    volumes:
      - ./tmp:/tmp
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=hra.settings.dev
      - DATABASE_URL=postgres://hra:hra@database:5432/hra
      - CACHE_URL=redis://redis:6379/

  pgadmin:
    depends_on:
      - database
    image: dpage/pgadmin4
    ports:
      - 8001:80
    environment:
      PGADMIN_DEFAULT_EMAIL: hra
      PGADMIN_DEFAULT_PASSWORD: hra

  shell:
    depends_on:
      - web
    image: ubuntu:xenial
    volumes:
      - .:/local

  localstack:
    image: localstack/localstack
    ports:
      - "4567-4583:4567-4583"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data
      - DEBUG=1
    volumes:
      - "./localstack:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
