# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionsnippet',
            name='summary',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
