# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_make_calltoactionsnippet_summary_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin_company_id',
            field=models.CharField(blank=True, default='health-research-authority', help_text='The bit after http://linkedin.com/company/ in your LinkedIn page URL', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube_channel_id',
            field=models.CharField(blank=True, default='UCdRaMooWKtc3YM5gkpB2FaA', help_text='The bit after https://www.youtube.com/channel/ in your YouTube channel URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter_handle',
            field=models.CharField(blank=True, default='hra_latest', help_text='Your Twitter username without the @, e.g. katyperry', max_length=255),
        ),
    ]
