# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsindexfeaturedpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='newspagerelateddocument',
            name='page',
        ),
        migrations.AddField(
            model_name='newspage',
            name='author',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.DeleteModel(
            name='NewsPageRelatedDocument',
        ),
    ]
