# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 14:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields
from django.utils.html import linebreaks


def convert_textfield_into_richtext(apps, schema_editor):
    NewsPage = apps.get_model('news', 'NewsPage')

    for page in NewsPage.objects.all():
        page.introduction = linebreaks(page.introduction)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20170511_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.RunPython(convert_textfield_into_richtext, migrations.RunPython.noop),
    ]
