# Generated by Django 2.2.12 on 2020-04-09 15:36

from django.db import migrations
import hra.utils.blocks
import hra.utils.models
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20200304_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', icon='title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('longdesc', wagtail.core.blocks.PageChooserBlock(help_text='If this image conveys infomation not given in the page text, provide a page with an full description for non-sighted users.', label='Long description', page_type=['standardpage.StandardPage'], required=False))])), ('quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.RichTextBlock()), ('quotee', wagtail.core.blocks.CharBlock(required=False)), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('embed', wagtail.embeds.blocks.EmbedBlock()), ('call_to_action', wagtail.core.blocks.StructBlock([('call_to_action', wagtail.snippets.blocks.SnippetChooserBlock(hra.utils.models.CallToActionSnippet)), ('side_text', wagtail.core.blocks.RichTextBlock())])), ('highlight', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock()), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])), ('table', wagtail.contrib.table_block.blocks.TableBlock(template='blocks/table_block.html')), ('lms_login', hra.utils.blocks.LMSLoginBlock()), ('cookie_options', wagtail.core.blocks.StructBlock([('measurement_desc', wagtail.core.blocks.RichTextBlock(help_text='Use this to describe how measurement cookies are used on the site. This section is shown only if the relevant cookies are actually in use.', label='Measurement cookies description')), ('necessary_desc', wagtail.core.blocks.RichTextBlock(help_text='Use this to describe how necessary cookies are used on the site.', label='Necessary cookies description'))])), ('anchor', hra.utils.blocks.AnchorBlock(help_text='Value to append to URL after # character'))]),
        ),
    ]
