# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_links', wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('title', wagtail.wagtailcore.blocks.TextBlock(help_text="Leave blank to use the page's own title", required=False))))),), blank=True)),
                ('footer_links', wagtail.wagtailcore.fields.StreamField((('column', wagtail.wagtailcore.blocks.StructBlock((('column_heading', wagtail.wagtailcore.blocks.TextBlock()), ('subitems', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('title', wagtail.wagtailcore.blocks.TextBlock(help_text="Leave blank to use the page's own title", required=False))), label='Sub-item')))))),), blank=True)),
                ('footer_secondary_links', wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock()), ('title', wagtail.wagtailcore.blocks.TextBlock(help_text="Leave blank to use the page's own title", required=False))))),), blank=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='footernavigationsnippet',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='primarynavigationsnippet',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='primarynavigationsubmenusnippet',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='primarynavigationsubmenusnippet',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='secondarynavigationsnippet',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='FooterNavigationSnippet',
        ),
        migrations.DeleteModel(
            name='PrimaryNavigationSnippet',
        ),
        migrations.DeleteModel(
            name='PrimaryNavigationSubmenuSnippet',
        ),
        migrations.DeleteModel(
            name='SecondaryNavigationSnippet',
        ),
    ]
