# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 14:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields
from django.utils.html import linebreaks


def convert_textfield_into_richtext(apps, schema_editor):
    FormPage = apps.get_model('forms', 'FormPage')

    for page in FormPage.objects.all():
        page.introduction = linebreaks(page.introduction)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_formpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formpage',
            name='introduction',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True),
        ),
        migrations.RunPython(convert_textfield_into_richtext, migrations.RunPython.noop),
    ]
