# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rec', '0006_remove_hra_office_add_approvals_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeepage',
            name='approvals_specialist',
            field=models.CharField(blank=True, max_length=255, verbose_name='Approvals Specialist'),
        ),
    ]
