# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchSummariesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255)),
                ('introduction', wagtail.wagtailcore.fields.RichTextField(blank=True)),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('social_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ResearchSummaryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('social_text', models.CharField(blank=True, max_length=255)),
                ('listing_title', models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255)),
                ('listing_summary', models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255)),
                ('harp_application_id', models.PositiveIntegerField(unique=True)),
                ('full_title', models.CharField(blank=True, editable=False, max_length=512)),
                ('iras_id', models.CharField(blank=True, max_length=255, verbose_name='IRAS ID')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=255)),
                ('sponsor_organisation', models.CharField(blank=True, max_length=255)),
                ('eudract_number', models.CharField(blank=True, max_length=255)),
                ('isrctn_number', models.CharField(blank=True, max_length=255, verbose_name='ISRCTN Number')),
                ('clinicaltrials_number', models.CharField(blank=True, max_length=255, verbose_name='Clinicaltrials.gov Identifier')),
                ('additional_reference_number_fields', models.CharField(blank=True, max_length=255)),
                ('duration_of_study_in_uk', models.CharField(blank=True, max_length=255, verbose_name='Duration of Study in UK')),
                ('research_summary_text', models.TextField(blank=True)),
                ('rec_name', models.CharField(blank=True, max_length=255)),
                ('rec_reference', models.CharField(blank=True, max_length=255)),
                ('date_of_rec_opinion', models.DateField(blank=True, null=True)),
                ('rec_opinion', models.CharField(blank=True, choices=[('unfavourable', 'Unfavourable Opinion'), ('favourable', 'Favourable Opinion'), ('further_unfavourable', 'Further Information Unfavourable Opinion'), ('further_favourable', 'Further Information Favourable Opinion')], max_length=64)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('data_collection_arrangements', models.CharField(blank=True, max_length=512)),
                ('research_programme', models.CharField(blank=True, max_length=512)),
                ('storage_license', models.CharField(blank=True, max_length=512)),
                ('rtb_title', models.CharField(blank=True, max_length=512, verbose_name='RTBTitle')),
                ('research_database_title', models.CharField(blank=True, max_length=255)),
                ('establishment_organisation', models.CharField(blank=True, max_length=255)),
                ('establishment_organisation_address_1', models.CharField(blank=True, max_length=255)),
                ('establishment_organisation_address_2', models.CharField(blank=True, max_length=255)),
                ('establishment_organisation_address_3', models.CharField(blank=True, max_length=255)),
                ('establishment_organisation_address_postcode', models.CharField(blank=True, max_length=32)),
                ('listing_image', models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='ResearchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('harp_study_type_id', models.PositiveIntegerField(editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'research type',
                'verbose_name_plural': 'research types',
            },
        ),
        migrations.AddField(
            model_name='researchsummarypage',
            name='research_types',
            field=modelcluster.fields.ParentalManyToManyField(to='research_summaries.ResearchType'),
        ),
        migrations.AddField(
            model_name='researchsummarypage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
