# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-10 13:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0033_remove_golive_expiry_help_text'),
        ('utils', '0002_make_calltoactionsnippet_summary_textfield'),
        ('standardpage', '0002_auto_20170509_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardIndexSectionPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='standardpagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='standardpagerelateddocument',
            name='page',
        ),
        migrations.AddField(
            model_name='standardindex',
            name='call_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.CallToActionSnippet'),
        ),
        migrations.AddField(
            model_name='standardindex',
            name='hero_introduction',
            field=models.CharField(blank=True, help_text='Short text to appear under page title', max_length=120),
        ),
        migrations.DeleteModel(
            name='StandardPageRelatedDocument',
        ),
        migrations.AddField(
            model_name='standardindexsectionpage',
            name='source_page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_pages', to='standardpage.StandardIndex'),
        ),
    ]
