# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-15 14:17
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields
from django.utils.html import linebreaks


def convert_textfield_into_richtext(apps, schema_editor):
    StandardIndex = apps.get_model('standardpage', 'StandardIndex')
    StandardPage = apps.get_model('standardpage', 'StandardPage')

    for page in StandardIndex.objects.all():
        page.introduction = linebreaks(page.introduction)
        page.save()

    for page in StandardPage.objects.all():
        page.introduction = linebreaks(page.introduction)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0004_standardpagepagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardindex',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='introduction',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.RunPython(convert_textfield_into_richtext, migrations.RunPython.noop),
    ]
