# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('standardpage', '0006_add_listing_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardindex',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
