# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('people', '0002_auto_20170509_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='personindexpage',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='listing_image',
            field=models.ForeignKey(blank=True, help_text='Choose the image you wish to be displayed when this page appears in listings', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='listing_summary',
            field=models.CharField(blank=True, help_text="The text summary used when this page appears in listings. It's also used as the description for search engines if the 'Search description' field above is not defined.", max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='listing_title',
            field=models.CharField(blank=True, help_text='Override the page title used when this page appears in listings', max_length=255),
        ),
        migrations.AddField(
            model_name='personpage',
            name='social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='personpage',
            name='social_text',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
