# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationbarsettings',
            name='text',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='notificationbarsettings',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
